/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.intersys.igestao.modulos.cadastro.produto;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author LUIS-GUSTAVO
 */
public final class ProdutoView extends javax.swing.JFrame {
    

  /**
   * Creates new form ProdutoView
   */
  public ProdutoView() {
    this.initComponents();
    this.inicializar();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblCodigo = new javax.swing.JLabel();
    tfCodigo = new javax.swing.JTextField();
    lblDescricao = new javax.swing.JLabel();
    tfDescricao = new javax.swing.JTextField();
    btnGravar = new javax.swing.JButton();
    btnHabilitarDesabilitar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tfaResposta = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(null);

    lblCodigo.setText("Código");
    getContentPane().add(lblCodigo);
    lblCodigo.setBounds(70, 0, 120, 14);
    getContentPane().add(tfCodigo);
    tfCodigo.setBounds(70, 20, 170, 20);

    lblDescricao.setText("Descrição");
    getContentPane().add(lblDescricao);
    lblDescricao.setBounds(70, 40, 90, 14);
    getContentPane().add(tfDescricao);
    tfDescricao.setBounds(70, 60, 170, 20);

    btnGravar.setText("Inserir");
    getContentPane().add(btnGravar);
    btnGravar.setBounds(70, 90, 90, 23);

    btnHabilitarDesabilitar.setText("Habilitar");
    getContentPane().add(btnHabilitarDesabilitar);
    btnHabilitarDesabilitar.setBounds(160, 90, 80, 23);

    tfaResposta.setColumns(20);
    tfaResposta.setRows(5);
    jScrollPane1.setViewportView(tfaResposta);

    getContentPane().add(jScrollPane1);
    jScrollPane1.setBounds(0, 120, 310, 140);

    setSize(new java.awt.Dimension(342, 359));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void inicializar() {
    ProdutoViewCtrl produtoViewCtrl = ProdutoViewCtrl.getInstancia();
    produtoViewCtrl.setProdutoView(this);
    produtoViewCtrl.inicializar();
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ProdutoView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnGravar;
  private javax.swing.JButton btnHabilitarDesabilitar;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblCodigo;
  private javax.swing.JLabel lblDescricao;
  private javax.swing.JTextField tfCodigo;
  private javax.swing.JTextField tfDescricao;
  private javax.swing.JTextArea tfaResposta;
  // End of variables declaration//GEN-END:variables

  public JButton getBtnGravar() {
    return btnGravar;
  }

  public void setBtnGravar(JButton btnGravar) {
    this.btnGravar = btnGravar;
  }

  public JButton getBtnHabilitarDesabilitar() {
    return btnHabilitarDesabilitar;
  }

  public void setBtnHabilitarDesabilitar(JButton btnHabilitarDesabilitar) {
    this.btnHabilitarDesabilitar = btnHabilitarDesabilitar;
  }

  public JLabel getLblCodigo() {
    return lblCodigo;
  }

  public void setLblCodigo(JLabel lblCodigo) {
    this.lblCodigo = lblCodigo;
  }

  public JLabel getLblDescricao() {
    return lblDescricao;
  }

  public void setLblDescricao(JLabel lblDescricao) {
    this.lblDescricao = lblDescricao;
  }

  public JTextField getTfCodigo() {
    return tfCodigo;
  }

  public void setTfCodigo(JTextField tfCodigo) {
    this.tfCodigo = tfCodigo;
  }

  public JTextField getTfDescricao() {
    return tfDescricao;
  }

  public void setTfDescricao(JTextField tfDescricao) {
    this.tfDescricao = tfDescricao;
  }

  public JTextArea getTfaResposta() {
    return tfaResposta;
  }

  public void setTfaResposta(JTextArea tfaResposta) {
    this.tfaResposta = tfaResposta;
  }
}
